bmad:
  enabled: false
  project_dir: _bmad
  version_tag: '@alpha'
  package_name: bmad-method
build:
  goflags: []
  ldflags: []
  output: bin
  parallel: 10
  platforms:
    - linux/amd64
    - darwin/amd64
    - darwin/arm64
    - windows/amd64
  tags: []
  trimpath: true
  verbose: false
  prebuild:
    strategy: ""
    batch_size: 0
    batch_delay: 0
    memory_limit: ""
    exclude: ""
    priority: ""
    verbose: false
docs:
  tool: ""
  port: 0
download:
  backoff_multiplier: 2
  enable_resume: true
  initial_delay_ms: 1000
  max_delay_ms: 30000
  max_retries: 5
  timeout_ms: 60000
  user_agent: mage-x-downloader/1.0
lint:
  disable_linters: []
  enable_all: false
  enable_linters: []
  golangci_version: latest
  skip_dirs: []
  skip_files: []
  timeout: 5m
project:
  binary: mage-x
  description: ""
  env: {}
  git_domain: github.com
  main: ""
  module: github.com/mrz1836/mage-x
  name: mage-x
  repo_name: ""
  repo_owner: ""
  version: ""
release:
  changelog: true
  draft: false
  formats:
    - tar.gz
    - zip
  github_token_env: GITHUB_TOKEN
  name_template: ""
  prerelease: false
speckit:
  enabled: false
  constitution_path: .specify/memory/constitution.md
  version_file: .specify/version.txt
  backup_dir: .specify/backups
  backups_to_keep: 5
  cli_name: specify-cli
  github_repo: git+https://github.com/github/spec-kit.git
  ai_provider: claude
test:
  auto_discover_build_tags: false
  auto_discover_build_tags_exclude: []
  bench_cpu: 0
  bench_mem: false
  bench_time: ""
  ci_mode:
    enabled: false
    format: auto
    context_lines: 20
    max_memory_mb: 100
    dedup: true
    output_path: .mage-x/ci-results.jsonl
  cover: false
  covermode: atomic
  coverpkg: []
  coverage_exclude: []
  exclude_modules:
    - ""
  integration_tag: ""
  integration_timeout: 30m
  parallel: 10
  race: false
  short: false
  shuffle: false
  skip_fuzz: false
  tags: ""
  timeout: 10m
  verbose: false
tools:
  custom: {}
  fumpt: latest
  yamlfmt: latest
  govulncheck: latest
  golangci_lint: latest
  mockgen: latest
  swag: latest
