build:
  goflags: []
  ldflags: []
  output: bin
  parallel: 10
  platforms:
    - linux/amd64
    - darwin/amd64
    - darwin/arm64
    - windows/amd64
  tags: []
  trimpath: true
  verbose: false
docker:
  build_args: {}
  cache_from: []
  default_registry: docker.io
  dockerfile: Dockerfile
  enable_buildkit: true
  labels: {}
  network_mode: ""
  platforms:
    - linux/amd64
    - linux/arm64
  registry: ""
  repository: ""
  security_opts: []
docs:
  tool: ""
  port: 0
download:
  backoff_multiplier: 2
  enable_resume: true
  initial_delay_ms: 1000
  max_delay_ms: 30000
  max_retries: 5
  timeout_ms: 60000
  user_agent: mage-x-downloader/1.0
lint:
  disable_linters: []
  enable_all: false
  enable_linters: []
  golangci_version: latest
  skip_dirs: []
  skip_files: []
  timeout: 5m
project:
  binary: mage-x
  description: ""
  env: {}
  git_domain: github.com
  main: ""
  module: github.com/mrz1836/mage-x
  name: mage-x
  repo_name: ""
  repo_owner: ""
  version: ""
release:
  changelog: true
  draft: false
  formats:
    - tar.gz
    - zip
  github_token_env: GITHUB_TOKEN
  name_template: ""
  prerelease: false
test:
  auto_discover_build_tags: false
  auto_discover_build_tags_exclude: []
  bench_cpu: 0
  bench_mem: false
  bench_time: ""
  cover: false
  covermode: atomic
  coverpkg: []
  coverage_exclude: []
  integration_tag: ""
  integration_timeout: 30m
  parallel: 10
  race: false
  short: false
  shuffle: false
  skip_fuzz: false
  tags: ""
  timeout: 10m
  verbose: false
tools:
  custom: {}
  fumpt: latest
  govulncheck: latest
  golangci_lint: latest
  mockgen: latest
  swag: latest
