name: Fortress Test Mage

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  test-mage-installation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Mage
        run: |
          echo "## Installing Mage"
          go install github.com/magefile/mage@latest

          echo "## Verifying Installation"
          which mage
          mage -version

          echo "## Mage installation successful ✅"

  test-mage-core:
    needs: test-mage-installation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - {name: "Help System", cmd: "mage -l", desc: "List all available targets"}
          - {name: "Version", cmd: "mage -version", desc: "Show mage version"}
          - {name: "Default Target", cmd: "mage", desc: "Run default target"}
          - {name: "Build", cmd: "mage build:default", desc: "Test build functionality"}
          - {name: "Clean", cmd: "mage build:clean", desc: "Test clean functionality"}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Test ${{ matrix.test.name }}
        run: |
          echo "## Testing: ${{ matrix.test.name }}"
          echo "Command: ${{ matrix.test.cmd }}"
          echo "Purpose: ${{ matrix.test.desc }}"
          echo "----------------------------------------"

          ${{ matrix.test.cmd }}

          echo "✅ ${{ matrix.test.name }} completed successfully"

  test-mage-namespaces:
    needs: test-mage-installation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        namespace:
          - {name: "Build", cmds: ["mage build:default", "mage build:clean"]}
          - {name: "Test", cmds: ["mage test:unit", "mage test:short"]}
          - {name: "Lint", cmds: ["mage lint:version"]}
          - {name: "Tools", cmds: ["mage tools:install"]}
          - {name: "Deps", cmds: ["mage deps:download"]}
          - {name: "Mod", cmds: ["mage mod:download"]}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Test ${{ matrix.namespace.name }} Namespace
        run: |
          echo "## Testing ${{ matrix.namespace.name }} Namespace"
          echo "========================================="

          # Source environment variables for tool versions
          if [ -f .github/.env.base ]; then
            source .github/.env.base
            echo "✅ Loaded tool versions from .github/.env.base"
          fi

          # Run commands based on namespace
          case "${{ matrix.namespace.name }}" in
            "Build")
              echo "### Running: mage build:default"
              mage build:default
              echo "### Running: mage build:clean"
              mage build:clean
              ;;
            "Test")
              echo "### Running: mage test:unit"
              mage test:unit
              ;;
            "Lint")
              echo "### Running: mage lint:default"
              mage lint:default || echo "Lint may not be fully configured"
              ;;
            "Tools")
              echo "### Running: mage tools:install"
              mage tools:install
              ;;
            "Deps")
              echo "### Running: mage deps:download"
              mage deps:download
              ;;
            "Mod")
              echo "### Running: mage mod:download"
              mage mod:download
              ;;
          esac

          echo ""
          echo "✅ ${{ matrix.namespace.name }} namespace test completed"

  test-mage-help:
    needs: test-mage-installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Mage
        run: go install github.com/magefile/mage@latest

      - name: Test Help System
        run: |
          echo "## Testing Mage Help System"
          echo ""

          echo "### List all targets"
          mage -l

          echo ""
          echo "### Verify namespace targets are visible"
          if mage -l | grep -q "build"; then
            echo "✅ Build namespace targets found"
          else
            echo "❌ Build namespace targets not found"
            exit 1
          fi

          if mage -l | grep -q "test"; then
            echo "✅ Test namespace targets found"
          else
            echo "❌ Test namespace targets not found"
            exit 1
          fi

          echo ""
          echo "✅ Help system working correctly"

  test-cross-platform:
    needs: test-mage-installation
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install and Test Mage on ${{ matrix.os }}
        run: |
          echo "## Testing Mage on ${{ matrix.os }}"

          # Install mage
          go install github.com/magefile/mage@latest

          # Test basic functionality
          mage -version
          mage -l

          # Run a simple build
          mage build:clean

          echo "✅ Mage works correctly on ${{ matrix.os }}"

  summary:
    needs: [test-mage-installation, test-mage-core, test-mage-namespaces, test-mage-help, test-cross-platform]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Mage Test Summary
        run: |
          echo "# 🪄 Mage Functionality Test Summary"
          echo ""
          echo "## Test Results"
          echo ""
          echo "| Test Suite | Status |"
          echo "|------------|--------|"
          echo "| Installation | ${{ needs.test-mage-installation.result }} |"
          echo "| Core Functions | ${{ needs.test-mage-core.result }} |"
          echo "| Namespaces | ${{ needs.test-mage-namespaces.result }} |"
          echo "| Help System | ${{ needs.test-mage-help.result }} |"
          echo "| Cross-Platform | ${{ needs.test-cross-platform.result }} |"
          echo ""

          # Determine overall status
          if [[ "${{ needs.test-mage-installation.result }}" == "failure" ]] || \
             [[ "${{ needs.test-mage-core.result }}" == "failure" ]] || \
             [[ "${{ needs.test-mage-namespaces.result }}" == "failure" ]] || \
             [[ "${{ needs.test-mage-help.result }}" == "failure" ]] || \
             [[ "${{ needs.test-cross-platform.result }}" == "failure" ]]; then
            echo "## ❌ Some Mage tests failed"
            exit 1
          else
            echo "## ✅ All Mage tests passed"
            echo ""
            echo "Mage is properly installed and functioning correctly across all tested scenarios."
          fi
